name: Prune unmanaged Markdown (wissen/content)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'WIRKLICH löschen? (false = Dry-Run)'
        required: true
        default: 'false'
        type: choice
        options: ['false','true']
      allowlist_extra:
        description: 'Zusätzliche Allowlist-Präfixe relativ zu wissen/content (kommagetrennt)'
        required: false
        default: ''
  # Optional automatischer Start nach SSOT-Sync:
  # workflow_run:
  #   workflows: ['SSOT → Markdown Sync (export_pfad; no image renaming; PR-gated)']
  #   types: [completed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: prune-unmanaged-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prune:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .   # wir rufen das Script mit absolutem Pfad auf
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Prune (Dry-Run/Real je nach Input)
        env:
          PRUNE_CONFIRM: ${{ github.event.inputs.confirm || 'false' }}
          # Feste Schutz-Prefixe + optionale Ergänzungen aus dem UI
          PRUNE_ALLOWLIST: de/docs,de/faq,en/faq${{ github.event.inputs.allowlist_extra && format(',{0}', github.event.inputs.allowlist_extra) || '' }}
        run: |
          python wissen/scripts/prune_unmanaged.py

      # OPTIONAL: leere Verzeichnisse entfernen (nur im Real-Run)
      - name: Remove empty directories
        if: ${{ github.event.inputs.confirm == 'true' }}
        run: |
          python - <<'PY'
          from pathlib import Path
          root = Path('wissen/content')
          removed = 0
          # Tiefste Ordner zuerst
          for d in sorted([p for p in root.rglob('*') if p.is_dir()],
                          key=lambda p: len(p.parts), reverse=True):
              try:
                  next(d.iterdir())
              except StopIteration:
                  d.rmdir(); removed += 1
              except Exception:
                  pass
          print(f"Removed {removed} empty dirs")
          PY

      - name: Stage changes
        if: ${{ github.event.inputs.confirm == 'true' }}
        run: |
          git add -A

      - name: Create Pull Request
        if: ${{ github.event.inputs.confirm == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/prune-unmanaged
          title: 'chore(wissen): prune unmanaged markdown'
          commit-message: 'chore(wissen): prune unmanaged markdown (auto)'
          labels: chore,cleanup
