name: Sync → Build → Deploy (Hugo / wissen)

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"   # stündlich um :17

jobs:
  sync:
    name: Sync from Google Sheet
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.diffcheck.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install pandas requests

      - name: Sync DE
        env:
          GSHEET_CSV_URL: ${{ secrets.GSHEET_CSV_URL }}
          LANG: de
          CONTENT_DIR: wissen/content/de
        run: python scripts/sync-from-sheet-hugo.py

      - name: Sync EN
        env:
          GSHEET_CSV_URL: ${{ secrets.GSHEET_CSV_URL }}
          LANG: en
          CONTENT_DIR: wissen/content/en
        run: python scripts/sync-from-sheet-hugo.py

      - name: Git stage
        run: |
          git config user.name  "gh-bot"
          git config user.email "gh-bot@users.noreply.github.com"
          git add wissen/content

      - name: Detect changes
        id: diffcheck
        run: |
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.diffcheck.outputs.changed == 'true'
        run: |
          git commit -m "content: sync from sheet (Hugo) – $(date -u +'%Y-%m-%d %H:%M')"
          git push

  build_deploy:
    name: Build & Deploy Hugo
    runs-on: ubuntu-latest
    needs: sync
    if: needs.sync.result == 'success' && needs.sync.outputs.changed == 'true'
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.146.0"
          extended: true

      - name: Build (Hugo)
        run: hugo --source wissen --minify

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:   ${{ secrets.SFTP_HOST }}
          port:     ${{ secrets.SFTP_PORT || 22 }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "public/*"
          remote_path: "${{ secrets.SFTP_TARGET }}"   # z.B. /kunden/www/vertaefelungen.de/wissen
          delete_remote_files: true
          sftp_only: true
